# Generated by Django 5.2.5 on 2025-08-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=50, verbose_name='Student ID')),
                ('FramID', models.IntegerField(verbose_name='Frame ID')),
                ('ClassID', models.IntegerField(verbose_name='Class ID')),
                ('Emotion', models.JSONField(verbose_name='Emotion Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Data',
                'verbose_name_plural': 'Student Data',
                'db_table': 'student_data',
                'indexes': [models.Index(fields=['studentID'], name='student_dat_student_2da74a_idx'), models.Index(fields=['ClassID'], name='student_dat_ClassID_0ffb4e_idx'), models.Index(fields=['FramID'], name='student_dat_FramID_9278e3_idx')],
            },
        ),
    ]
